#!/usr/bin/env php
<?php

use Templator\Dev;

if (strpos(PHP_SAPI, 'cli') === false) {
	fwrite(STDERR, 'Requires CLI PHP' . PHP_EOL);

	exit(1);
}

if (version_compare('7.3.0', PHP_VERSION, '>')) {
	fwrite(STDERR, 'Requires PHP 7.3.' . PHP_EOL);

	exit(1);
}

define('VERSION', '1.0');

if (!include 'src/Dev.php') {
	fwrite(
		STDERR,
		'ERROR: Could not find Admin.php' . PHP_EOL
	);

	exit(1);
}

$opts = getopt('hv', [
	'help',
	'version::',
	'tmpl-dir:',
	'http-dir:',
	'min::',
	'cmd:'
]);

if (@$opts['h'] === false or @$opts['help'] === false) {
	fwrite(
		STDOUT,
		sprintf(<<<__
Templator v%s

Usage: templator [options]

Required options:

  --tmpl-dir <path>  File path to templates directory
  --http-dir <path>  File path to HTTP directory
  --cmd <command>    Command to execute (see below)

<command> options:
  "make-server" 	 Create .htaccess and index.php files
  "make-example"     Create sample template files
  "make-dev-example" Create starter dev framework
  "make-css"         Build the CSS files
  "make-js"          Build the JS files

Command options:
  --min              Minify output (only for --make-css and --make-js)
  --path             URL path (only for --make-css and --make-js)

Miscellaneous options:

  -h|--help          Prints this usage information
  --version          Prints the version and exits
__
			, VERSION) . PHP_EOL . PHP_EOL
	);

	exit(0);
}

if (@$opts['v'] === false or @$opts['version'] === false) {
	fwrite(
		STDOUT,
		sprintf('v%s', VERSION) . PHP_EOL
	);

	exit(0);
}

foreach (['tmpl-dir', 'http-dir'] as $v) {
	//if not sent use assumtions
		// fwrite warning
	if (!@$opts[$v] or !strlen($opts[$v]) or !is_dir($opts[$v]) or !is_readable($opts[$v])) {
		fwrite(
			STDERR,
			sprintf('ERROR: Could not get directory from argument --%s', $v) . PHP_EOL
		);

		exit(1);
	}
}

$path = (string)@$opts['path'];
$min = isset($opts['min']);

$Dev = new Dev($opts['tmpl-dir'], $opts['http-dir']);

switch ((string)@$opts['cmd']) {
	case 'make-server':
		$Dev->makeDevServer();
		break;
	case 'make-dev-example':
		$Dev->makeDevExample();
		break;
	case 'make-example':
		$Dev->makeExample();
		break;
	case 'make-css':
		$Dev->makeCSS($path ?: 'css', $min);
		break;
	case 'make-js':
		$Dev->makeJS($path ?: 'js', $min);
		break;
	default:
		fwrite(
			STDERR,
			'ERROR: Unknown command (see --help for list of commands)' . PHP_EOL
		);

		exit(1);
}

exit(0);
