name: Run PHP Tests in Docker

on:
  push:
    branches: [ main ]
  pull_request:

env:
  TEST_IMG_NAME: templator-test-php

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.3', '8.4', '8.5' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image (PHP ${{ matrix.php-version }})
        run: |
          docker build --build-arg PHP_VERSION=${{ matrix.php-version }} -t ${{ env.TEST_IMG_NAME }}:${{ matrix.php-version }} .

      - name: Run container and execute tests
        run: |
          docker run --rm -e XDEBUG_MODE=coverage ${{ env.TEST_IMG_NAME }}:${{ matrix.php-version }} vendor/bin/phpunit

      - name: Run container and execute analyse
        run: |
          docker run --rm ${{ env.TEST_IMG_NAME }}:${{ matrix.php-version }} vendor/bin/phpstan analyse -c phpstan.neon
